version: '3'
services:
  php:
    build: build/php
    depends_on:
      - rabbitmq
      - redis
    expose:
      - '9000'
    volumes:
      - ./app:/var/www/html/symfony:cached
      - ./logs:/var/log
  web:
    build: build/nginx
    restart: always
    ports:
      - '81:80'
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html/symfony:cached
      - ./logs:/var/log/nginx
  redis:
    env_file:
      - ./app/.env
    image: redis:latest
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
  rabbitmq:
    env_file:
      - ./app/.env
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"
